### ISSUE TITLE
Does this load embeded materials?

### ISSUE THREAD

**Issue by BenJ778** [tidewise/gui-fbx_osg#3]
hi does this fbx plugin load, skeletal animation, facial blend shapes, morphs, PBR textures and embeded textures?

basically im asking if this works perfectly without any issues with textures not loading or certain animations not loading in osg..
just want to know if this is the best option for adding FBX importing to our osg software.

your reply is much appreciated.

**Comment by doudou** [comment]
This is essentially OSG's own FBX plugin but packaged as a separate repository so that I can use it on older OSG versions.

So, it can only do what OSG's own functionality can do.
